language: ruby
rvm:
- 2.3
before_script:
- npm install -g gulp-cli
- npm install
- gem install jekyll jekyll-paginate jekyll-feed jekyll-sitemap
script:
- jekyll build
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAJX5RKV6KMD42SXOA
  secret_access_key:
    secure: "LTJiVcqWGYcBEvIjFPDjGUicK1pZr8y6RrGBWmUVXQrIooFvTB/39cJLqtufde3MW7TPsAv/Gftwny3ybODGvDQMxggbT2mNekWnii/nATq6pLR1p48/lm9sTz1mPmpg1/5CYUFOd+ynFmlHQDAwoIFxwjg0/KX+27/0/gBPuNqkp+zqBp7saIeR/Tb0a+NT7Jcnjb3vQWNr/ZDpZSqOssGKz4YptiLDs+BW4AAQL+KwRB+yQXJXv2PYzvbbuSZUX+6obihoyEjE7110up4jbVLXy5Zd9CPSN5kbP4V/nvNN9RKm5W9BKu98TXeWEk/8EqNpC3kenxkZDLMPz9XXQWABe+y29jzz8j4G4UUfZa5STCmzQN6XwDSPcbwjpTp9icaKz2KvVNrBpmu7HaXhB6bJBxLrF/Mjkfb+MUAwA8/oxalxNozxrSwsFJ1FM9BsBOCZ82WvOV2K9R9y8VwQ7dUxrErh5H8FzsDVHaGTnEmI7eOeDEGJMxzzV4Kbi2FAKXE3bA56DQn+2N61Q+maSXeUr0nbpXmo3oWDGtLOy98g5aEpk6FH+y82NV541PdFFvDgFavF17DeM+OhVinJME0hF3IpKc2cJPp/k0D/54RS+b+jijyOW51N14X+x7bEW1rck1kLzr2gu8BcL68HxTaEdm/4uqqwtc/44bcElhI="
  bucket: patrickmcdavid.com
  local-dir: _site
  acl: public_read
  cache_control: max-age=120
  on:
    repo: ehippy/blog
